### ISSUE TITLE
Error after adding spine extension to project

### ISSUE THREAD

**Issue by fuderty** [defold/extension-spine#142]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-06-08T06:51:04.421732</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bd9d5a1025768a9f6b7acaaa73c874385e7c35e4</td></tr>
<tr><td>Defold engine sha</td><td>cb8b34230bd42a5e0b68c12441657f06485562a6</td></tr>
<tr><td>Defold version</td><td>1.4.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"8cf784940ee14a55a853bfbc09c45283"'>8cf784940ee14a55a853bfbc09c45283</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 536.67</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
```
com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException.class com.google.protobuf.UninitializedMessageException: Message missing required fields: spine_json, atlas
    at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:475)
    at com.dynamo.spine.proto.Spine$SpineSceneDesc$Builder.build(Spine.java:560)
    at com.dynamo.spine.proto.Spine$SpineSceneDesc$Builder.build(Spine.java:501)
    at editor.protobuf$pb_builder_raw$builder_fn.invoke(protobuf.clj:435)
    at editor.protobuf$map__GT_pb.invokeStatic(protobuf.clj:446)
    at editor.protobuf$map__GT_str.invokeStatic(protobuf.clj:570)
    at editor.protobuf$map__GT_str.invoke(protobuf.clj:570)
    at editor.protobuf$map__GT_str.invokeStatic(protobuf.clj:571)
    at editor.protobuf$map__GT_str.invoke(protobuf.clj:570)
    at clojure.core$partial$fn.invoke(core.clj:2624)
    at editor.resource_node$fn.invokeStatic(resource_node.clj:74)
    at editor.resource_node$fn.invoke(resource_node.clj:68)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
```

**Comment by britzl** [comment]
Which version of the Spine extension are you using?

https://github.com/defold/extension-spine/releases

The latest version is compatible with Defold 1.4.8 and you seem to be using Defold 1.4.6. Could you please update Defold to 1.4.8 and try the latest extension version?

**Comment by AGulev** [comment]
requested info wasn't provided
